FROM ubuntu:22.04

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /app

# Update package lists and install required packages
RUN apt-get update && apt-get install -y \
    wget \
    gcc \
    g++ \
    python3-dev \
    python3-venv \
    python3-pip \
    openjdk-17-jre-headless \
    libbz2-dev \
    libcurl4 \
    libkrb5-dev \
    zlib1g-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy application files
COPY server_tsspredator /app/server_tsspredator
COPY requirements.txt /app
COPY setup.py /app
COPY server_tsspredator/TSSpredator.jar /app

# Download bedGraphToBigWig and set execute permissions
RUN wget https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig -P /app && \
    chmod +x /app/bedGraphToBigWig

# Create a Python virtual environment and install dependencies
RUN python3 -m venv /app/env_tss_predator_celery
ENV PATH="/app/env_tss_predator_celery/bin:$PATH"
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install -r requirements.txt

# Install the server package in editable mode
RUN pip install -e .

# Clean up build files
RUN rm -rf /app/requirements.txt /app/setup.py

# Expose the application port
EXPOSE 5001

# Set environment variables
ENV TSSPREDATOR_DATA_PATH="/data"
ENV TSSPREDATOR_SERVER_LOCATION="/app"
ENV TSSPREDATOR_TEMPDATA="/tmpData"
ENV TSSPREDATOR_REDIS_HOST="redis"

# Run the application via gunicorn
CMD ["gunicorn", "--workers", "6", "--timeout", "500", "--graceful-timeout", "500", "--bind", "0.0.0.0:5001", "wsgi:tsspredator"]
